# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notegen < Formula
  desc "Simple utility for formatting your markdown notes"
  homepage "https://github.com/justsharan/notegen"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justsharan/notegen/releases/download/v0.1.0/notegen_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "b672d07d4688e87abdd151f12e6c654b7a3c4a1aec6cc880bd6cd30fc2edbfe0"

      def install
        bin.install "notegen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justsharan/notegen/releases/download/v0.1.0/notegen_0.1.0_Darwin_arm64.tar.gz"
      sha256 "a27ac53b61d0a981929fbec694f4108951e270225ea8d5fb13ffea6fd3229220"

      def install
        bin.install "notegen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justsharan/notegen/releases/download/v0.1.0/notegen_0.1.0_Linux_arm64.tar.gz"
      sha256 "93e9922b8d84e0ef0b9b09a56d0a2d7b0afef6620c3688d87d9514faeec09c0d"

      def install
        bin.install "notegen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/justsharan/notegen/releases/download/v0.1.0/notegen_0.1.0_Linux_x86_64.tar.gz"
      sha256 "4aa513fe87403e9dc83d437b6319b34e88ed5df85d763ce75c1fd63ba2c9a24d"

      def install
        bin.install "notegen"
      end
    end
  end
end
